master/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/our-process', to: 'static_pages#our_process'

  get '/testing-options', to: 'static_pages#testing_options'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

master/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def our_process
  end

  def testing_options
  end
end

master/app/helpers/application_helper.rb
module ApplicationHelper
end

master/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

master/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    DNA Testing
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Testing Options", testing_options_path %></li> 
      <li><%= link_to "Our Process", our_process_path %></li>
    </ul>
  </nav>
</footer>

master/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">HSDesignHouse</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Testing Options", testing_options_path %></li> 
      <li><%= link_to "Our Process", our_process_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

master/app/views/layouts/_rails_default.html.erb
<!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

master/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
 <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

master/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

master/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

master/app/views/static_pages/our_process.html.erb
<h1>StaticPages#our_process</h1>
<p>Find me in app/views/static_pages/our_process.html.erb</p>

master/app/views/static_pages/testing_options.html.erb
<h1>StaticPages#testing_options</h1>
<p>Find me in app/views/static_pages/testing_options.html.erb</p>